<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-07-31T08:14:10 IST" name="TestNG" finished-at="2023-07-31T08:14:25 IST" duration-ms="14565">
    <groups>
    </groups>
    <test started-at="2023-07-31T08:14:10 IST" name="Test" finished-at="2023-07-31T08:14:25 IST" duration-ms="14565">
      <class name="com.obsqura.rmartSuperMarket.testscript.ManageCategoryTest">
        <test-method is-config="true" signature="initializeBrowser(java.lang.String)[pri:0, instance:com.obsqura.rmartSuperMarket.testscript.ManageCategoryTest@335b5620]" started-at="2023-07-31T08:14:10 IST" name="initializeBrowser" finished-at="2023-07-31T08:14:22 IST" duration-ms="11320" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initializeBrowser -->
        <test-method signature="verifyWhetherTheUserAbleToAddValuesInManageCategory()[pri:0, instance:com.obsqura.rmartSuperMarket.testscript.ManageCategoryTest@335b5620]" started-at="2023-07-31T08:14:22 IST" name="verifyWhetherTheUserAbleToAddValuesInManageCategory" finished-at="2023-07-31T08:14:24 IST" duration-ms="2280" status="FAIL">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[Cannot invoke "org.apache.poi.ss.usermodel.Cell.getStringCellValue()" because "c" is null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: Cannot invoke "org.apache.poi.ss.usermodel.Cell.getStringCellValue()" because "c" is null
at utilities.ExcelUtility.getString(ExcelUtility.java:129)
at com.obsqura.rmartSuperMarket.testscript.ManageCategoryTest.verifyWhetherTheUserAbleToAddValuesInManageCategory(ManageCategoryTest.java:15)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyWhetherTheUserAbleToAddValuesInManageCategory -->
        <test-method is-config="true" signature="browserQuit(org.testng.ITestResult)[pri:0, instance:com.obsqura.rmartSuperMarket.testscript.ManageCategoryTest@335b5620]" started-at="2023-07-31T08:14:24 IST" name="browserQuit" finished-at="2023-07-31T08:14:25 IST" duration-ms="830" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=verifyWhetherTheUserAbleToAddValuesInManageCategory status=FAILURE method=ManageCategoryTest.verifyWhetherTheUserAbleToAddValuesInManageCategory()[pri:0, instance:com.obsqura.rmartSuperMarket.testscript.ManageCategoryTest@335b5620] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- browserQuit -->
      </class> <!-- com.obsqura.rmartSuperMarket.testscript.ManageCategoryTest -->
    </test> <!-- Test -->
  </suite> <!-- TestNG -->
</testng-results>
